[project]
name = "otel"
version = "0.2.0.9000"
type = "package"
title = "OpenTelemetry R API"
description = '''
High-quality, ubiquitous, and portable telemetry to enable
effective observability. OpenTelemetry is a collection of tools,
APIs, and SDKs used to instrument, generate, collect, and export
telemetry data (metrics, logs, and traces) for analysis in order to
understand your software's performance and behavior.
This package implements the OpenTelemetry API:
<https://opentelemetry.io/docs/specs/otel/>.
Use this package as a dependency if you want to instrument your R
package for OpenTelemetry.'''
license = "MIT + file LICENSE"

[[project.authors]]
name = "Gábor Csárdi"
email = "csardi.gabor@gmail.com"
roles = [
    "aut",
    "cre",
]

[project.urls]
bugreports = "https://github.com/r-lib/otel/issues"
homepage = "https://otel.r-lib.org"
source = "https://github.com/r-lib/otel"

[dependencies]
R = ">= 3.6.0"

[dependency-groups.dev]
callr = "*"
cli = "*"
glue = "*"
jsonlite = "*"
otelsdk = "*"
processx = "*"
shiny = "*"
spelling = "*"
testthat = ">= 3.0.0"
utils = "*"
withr = "*"

[dependency-groups.website]
tidytemplate = { git = "https://github.com/tidyverse/tidytemplate.git", ref = "tidyverse/tidytemplate" }

[config.testthat]
edition = 3

[description]
Additional_repositories = "https://github.com/r-lib/otelsdk/releases/download/devel"
Encoding = "UTF-8"
Roxygen = "list(markdown = TRUE)"
RoxygenNote = "7.3.2.9000"
